Add support for plurals
appKODE/utas pull request #17
Opened 2023-06-02 00:00 UTC by dimsuz

2023-06-02 00:09 UTC, dimsuz commented on src/android_gen.rs
> +
не писал пока ни тестов в parse.rs, ни тут.

2023-06-02 00:09 UTC, dimsuz commented on src/android_gen.rs
>  }
тут тоже наверное надо будет добаавить типа `plurals_str`

2023-06-02 00:09 UTC, dimsuz commented on src/parse.rs
> +            .value;
вот тут borrow checker меня победил (на сегодня). 

Парсим `ru:one = X, ru:many = Y, итд`

Идея базовая такая: взять из мапы LocalizedString для локали, в ней лежит вектор с plurals, и пушнуть в неё новый плурал. Если нет ещё для локала LocalizedString, создать.

Тут я осознал, что я-то в мапу её при этом не кладу, get_or_insert это от Option.

Может он из-за этого был несчастен.

Значит сделаю ещё один подход потом.

2023-06-02 00:09 UTC, dimsuz commented on src/parse.rs
> +            .value;
Хотя всё равно, не кладу, ну и что, должно срботать. Если у тебя будет интерес, посмотри, может ты поймёшь что ему не нравится, у меня пока не срабатывает понималка (может на свежую голову)

2023-06-02 21:15 UTC, TrueWarg requested changes

2023-06-02 21:15 UTC, TrueWarg commented on src/parse.rs
> +            println!("skipped key \"{}\" because can't split into locale and quantity", locale_name_and_quantity);
А, блин. Так-то еще может и ru быть указано без. Надеюсь, мне померещилоь, иначе жопошло обрабатыать

2023-06-02 21:15 UTC, TrueWarg commented on src/parse.rs
> +            .value;
Если я правильно понял, тут ошибка, что из index map нельзя вытащить значение, потому что сама мапа им владеет. Ты не можешь передать владение сюда, пока есть что-то другое, что "захватило" значение.
Поэтому ты можешь передать или ссылку, которая будет ссылаться на это значение из мапы (вот на счет мутабельной - хз, но по идее тут дожно прокатить), либо удалить его из мапы (remove возвращает элемент), тогда владение перейдет в вызывающий код, и ты со значением можешь делать что захочешь. Правда, его потом нужно будет вставить обратно, я так, кстати в код гене и делал.

2023-06-02 23:21 UTC, dimsuz commented on src/parse.rs
> +            .value;
А, похоже!

Я просто думал как бы просто достать из мапы по mut-ссылке и прямо там поправить, как бы внутри мапы. Но видимо не так что-то сделал.

Если я ставлю `&` перед всем выражением (как компилятор предлагает, кстати), то он мне начинает писать другую ошибку, типа "ты создаёшь временную переменную и слишком рано её уничтожаешь", это я ещё меньше понимаю.

Попробую ещё завтра другой подход или на части разбить чуть, чтобы лучше понимать.

2023-06-02 23:23 UTC, dimsuz commented on src/parse.rs
> +    quantity: String,
Я думал тоже об этом, но потом подумал, что вроде бы мы _ровно_ эти же значения потом будем писать, и есть ли смысл делать enum, если матчить потом будем только для того, чтобы их же создать... Но можно и сделать будет, если будет польза!

2023-06-02 23:25 UTC, dimsuz commented on src/parse.rs
> +            println!("skipped key \"{}\" because can't split into locale and quantity", locale_name_and_quantity);
У меня сначала были мысли тоже, что так может быть, но потом я понял, что, кажется, нет.

Потому что если есть plurals, то ты в коде должен делать `context.getPlural` вместо `context.getString` и в этом месте ты не можешь проверять в каком локале что лежит - либо один метод зовёшь, либо другой.

Поэтому я подумал что смысла проверять нет, либо так либо так. Но может я чего-то забыл, надо проверить, конечно, есть ли такая дичь что рзные стили в одном.

2023-06-03 10:51 UTC, dimsuz commented on src/parse.rs
> +    );
запарился везде `to_string` писать. наверное, надо передлывать всё на `Map<&str, &value>`, но пока такого я боюсь.

2023-06-03 10:54 UTC, TrueWarg approved these changes

2023-06-03 10:54 UTC, merged

2023-06-03 10:58 UTC, dimsuz commented on src/android_gen.rs
>  }
Мне тоже кажется, лучше оставить тестов и там и там! Нравится, что есть и парсинговые и более высокоуровневые. Скорее даже первые (мои) можно было бы выкинуть, а эти оставить.