Add iOS Generation
appKODE/utas pull request #32
Opened 2023-09-06 09:01 UTC by Nazeebo

I added generation for iOS with new agrument for platform. Cloned all structures and examples from android, didn't know what to do with them.
There are few moments requiring improvements imo, I hope you would help in resolving them. I don't know Rust enough to resolve them myself.

Tests will be in another PR because I want them to be atomic.

Example of generated files:
Source file:

```
[[Src1]]
  [lorem]
    en = Lorem %d ipsumkekum
    ru = Лорем %d ипсумкекум

  [ooo]
    en = Ooooo %@ ooooO 
    ru = Ооооо %@ ооооО
```

<img width="230" alt="Directory structure" src="https://github.com/appKODE/utas/assets/16734454/aa9077b1-39cd-4727-99c4-0fb48d4b9bdb">

en.lproj/Localizable.strings:
```
"lorem" = "Lorem %d ipsumkekum";
"ooo" = "Ooooo %s ooooO";
```

2023-09-06 10:25 UTC, Nazeebo commented on src/ios_gen.rs
> +                    };
Might be a better way to do it. Also now there is problem that files are created even if there is no plurals or singles (very rare case but nonetheless)

2023-09-06 10:40 UTC, Nazeebo commented
Also there is a problem that parsing transforms %@ to %s, on iOS we need it to stay %@

2023-09-06 11:23 UTC, TrueWarg requested changes
Тесты для андроида надо поправить все равно, так как добавился аргумент в cli

2023-09-06 11:23 UTC, TrueWarg commented on src/ios_gen.rs
> +            .write(true)
о, надо будет линтер в ci добавить =)

2023-09-06 11:23 UTC, TrueWarg commented on src/ios_gen.rs
> +            if !locale_code_supported_in_ios(&locale.value) {
Я вот вижу, добавлял хак в андроидой части с LANG_WITH_REGION_RE,  у айос с этим не будет проблем?

2023-09-06 11:23 UTC, TrueWarg commented on src/ios_gen.rs
> +                    };
nit: Мне кажется, в таком случае line.format() лишний, можно сразу тут сформатнуть.
Иначе тут допущение, что formatted матчится строго с lines.value, то есть имеет одинаковый порядок и размер, что в общем-то ожидаемо, но чисто по смыслу может быть не всегда, например каждая строка из lines может сформатировать в две с переносотм.

2023-09-06 11:23 UTC, TrueWarg commented on src/ios_gen.rs
> +                    };
По созданию файла можно погуглить какую-нибудт ленивость на открытие/создание или дедовсих способом реализвоать это самому. Но вообще я бы забил, если реально редкий и больших проблем не вызывает

2023-09-06 11:23 UTC, TrueWarg commented on src/ios_gen.rs
> +    return true;
так получается это вооще лишнее или будет доделываться?

2023-09-06 11:24 UTC, Nazeebo commented on src/ios_gen.rs
> +            if !locale_code_supported_in_ios(&locale.value) {
Не, нам не нужны эти r

2023-09-06 11:24 UTC, Nazeebo commented on src/ios_gen.rs
> +    return true;
хз, решил оставить, если вдруг появится необходимость фильтр сделать, могу убрать

2023-09-06 15:35 UTC, Nazeebo commented on crates/file/src/file.rs
> +                if item.file_name() != ".DS_Store" {
Так, да, это нужно в функциях в file.rs, потому что get_all_file_paths используется только внутри file.rs
И используются несколько раз:

```
/// Check if all files in dirs have the same content and paths to files with contents
pub fn dirs_contents_are_same(dir1: impl AsRef<Path>, dir2: impl AsRef<Path>) -> Result<bool> {
    let mut paths1 = get_all_file_paths(&dir1.as_ref())?;
    let mut paths2 = get_all_file_paths(&dir2.as_ref())?;
```

пока не особо не представляю как фильтр навесить в каждом вызове, кажется, что лучше все-таки внутри функции фильтровать

2023-09-06 15:43 UTC, dimsuz approved these changes

2023-09-06 16:18 UTC, TrueWarg commented on src/main.rs
> +    platform: String,
да можно запихнуть и проверить, но я не помню, чтобы Parser работал для enum нормально

2023-09-07 13:11 UTC, Nazeebo commented on src/main.rs
> +    platform: String,
Если вы не против, на это туду оставил

2023-09-08 18:57 UTC, TrueWarg approved these changes
@Nazeebo @dimsuz а в итоге с dedup ошибкой разобрались?

2023-09-11 11:56 UTC, dimsuz commented
Was going to merge this, but noticed that CI has failed due to some android-gen tests not passing:

https://github.com/appKODE/utas/actions/runs/6110195317/job/16627470978?pr=32

Is this fixable?

2023-09-11 12:17 UTC, merged