iOS. Single file generation
appKODE/utas pull request #34
Opened 2023-09-12 14:50 UTC by Nazeebo

**Problems:** 
1) on iOS we expect one Localizable file for single strings and one Localizable file for plurals. Right one the script generates for every txt separate files
2) script does not ignore system files and the script fails

**What's done:**
1) I rewrote ios generation logic to:
    - accumulate parsed files
    - accumulate generations for the parsed files
    - writes accumulated generations to output files
2) I added some "logs" to failed unwraping

2023-09-14 15:07 UTC, TrueWarg requested changes

2023-09-14 15:07 UTC, TrueWarg commented on src/ios_gen.rs
> +            result.insert(locale, current_lines_for_locale.to_owned());
Хм, раз все равно берешь мутабельное, то тут можно попробовать
```
 result.get_mut(&locale)
   .unwrap_or_default()
   .value
   .extend(lines.value);
   ```
   То есть менять in place. Правда, я не понмю, покатит ли с unwrap_or_default

2023-09-14 15:07 UTC, TrueWarg commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
А ошибка разве не логируется и так? В ней будет указан путь к файлу, а у тебя просто строка.

2023-09-14 15:11 UTC, TrueWarg commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
+ это https://github.com/appKODE/utas/pull/34#discussion_r1326072285

2023-09-14 16:44 UTC, Nazeebo commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
Когда я дебажил эту ошибку, там просто текст из обработки вызова функции писался, деталей понятно не было, но согласен, что expect - плохое решение

2023-09-17 21:27 UTC, dimsuz commented on src/ios_gen.rs
> +    let generated_files: Vec<_> = sources.iter().filter_map( |src| {
Да, раз всё время `Some` внутри. Вроде даже просто `.map` хватит.

2023-09-17 21:27 UTC, dimsuz commented on src/parse.rs
> +    dedup_keys(&path, &temp_file).map_err(|error| (error.to_string() + "failed to dedup keys").to_string())?;
по идее надо ещё пробельчик

```suggestion
    dedup_keys(&path, &temp_file).map_err(|error| (error.to_string() + " failed to dedup keys").to_string())?;
```

2023-09-17 21:27 UTC, dimsuz commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
Может можно сделать как выше, типа `.map_error { |err| "file open failed: " + err }`, чтобы и исходная сохранилась и пояснение добавилось. (`map_error` это я для примера, не помню как правильная функция называется, но что-то такое должно быть).

Ну и expect-ы ниже можно сделать по той же модели.

2023-09-17 21:27 UTC, dimsuz commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
А, ну и всё таки я бы тоже не делал тут `expect`, это приводит к паникам без шанса вызывающей стороне обработать ошибку. Можно было бы просто помапить ошибку сопроводив доп строками и оставить `?`.

Я так уже делаю вот тут:

https://github.com/appKODE/utas/blob/5f008eceee3d646f8b9f4853632a74f2b15fcaf7/src/parse.rs#L88

(только тут ошибка теряется, ты как раз тоже поправил это выше).

2023-09-26 15:01 UTC, Nazeebo commented on src/ios_gen.rs
> +            result.insert(locale, current_lines_for_locale.to_owned());
текущая реализация Default не распространяется на мутабельное, есть идеи как обойти?

<img width="889" alt="Screenshot 2023-09-26 at 16 52 56" src="https://github.com/appKODE/utas/assets/16734454/dd181061-5b9a-48ca-8d4c-0bc4c6e85ce3">

+ extend нельзя использовать в цепочке вызовов, нужно другая функция, если попытаться сделать так

```
            let extended_lines = result.get_mut(&locale)
                .cloned()
                .unwrap_or_default()
                .value
                .extend(lines.value);

            result.insert(locale, extended_lines);
```

2023-09-26 16:01 UTC, Nazeebo commented on src/ios_gen.rs
> +            result.insert(locale, current_lines_for_locale.to_owned());
Есть ощущение, что при таком варианте просто не запишется никакое значение, потому что default создастся в отрыве от значения

<img width="716" alt="Screenshot 2023-09-26 at 18 01 10" src="https://github.com/appKODE/utas/assets/16734454/265764d6-ba70-4fe9-83ca-27a8d636109d">

2023-09-26 16:03 UTC, Nazeebo commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
map_err и правда не то, что нужно. есть идеи как называется то, что предлагаешь?)
<img width="1106" alt="Screenshot 2023-09-26 at 17 56 27" src="https://github.com/appKODE/utas/assets/16734454/6c609399-6d1b-4b94-aaf8-1bc27f539c04">

2023-09-27 12:56 UTC, Nazeebo commented on src/ios_gen.rs
> +            result.insert(locale, current_lines_for_locale.to_owned());
Подтверждаю, default mut получается оторванным от словаря значением, которое не изменяет в словаре ничего. Оставляю пока так всю конструкцию

2023-09-29 12:02 UTC, TrueWarg approved these changes

2023-09-29 12:02 UTC, TrueWarg commented on src/ios_gen.rs
> +            result.insert(locale, current_lines_for_locale.to_owned());
Ок.
Но у меня получилось через entry
```
   let mut result: HashMap<String, String> = HashMap::new();
   result.insert("kek".to_string(), "Checbu".to_string());
   
   println!("{:?}", &result);
   result
      .entry("kek".to_string())
      .or_insert("".to_string())
      .push_str("rec");
      
    result
      .entry("lol".to_string())
      .or_insert("".to_string())
      .push_str("Lalka");
      
     println!("{:?}", &result);
     
 // {"kek": "Checbu"}
 // {"kek": "Checburec", "lol": "Lalka"}
```

2023-09-29 12:04 UTC, TrueWarg commented on src/parse.rs
> +    let f = FsFile::open(path).expect("File opening failed");
надо вызвать макрос anyhow!
https://github.com/appKODE/utas/pull/34#discussion_r1326072285

2023-10-22 09:46 UTC, TrueWarg approved these changes

2023-10-22 09:46 UTC, merged