iOS. Filling missing translation with default language
appKODE/utas pull request #35
Opened 2023-10-23 12:04 UTC by Nazeebo

There was a problem with fallback value in iOS: it returns the key if there is no value for it. Base language only substitudes the whole file if it's missing. I thought I could fix it with our codegen library. But plurals and calls from Core are still problematic.

So I added function that fills all missing translations with default language
Also added parameter for file_name, not helpful for android but couldn't isolate it. I probably could keep it in local changes but it would hurt the next generation of developers :)

2023-11-07 21:05 UTC, TrueWarg requested changes

2023-11-07 21:05 UTC, TrueWarg commented on src/ios_gen.rs
> +impl Hash for Line {
Так будет много коллизий, разве derive Hash автомтом не может тут переопределить?

2023-11-07 21:05 UTC, TrueWarg commented on src/ios_gen.rs
> +fn fill_absent_translations(map: &mut HashMap<Locale, StrLines>, default_lang: &Option<String>) {
Я в предыдущем пулл реквесте писал как можно мапить ошибки в anyhow и при этом возвращать Result. Давай тут сделам так

2023-11-17 12:50 UTC, dimsuz commented on src/main.rs
> +    file_name: Option<String>,
нужен коммент о том, что это за имя файла. и может назвать переменную тож получше, сходу неясно. и доков в комманд-лайн `--help` по-хорошему бы тоже про неё добавить.

2023-11-17 13:53 UTC, Nazeebo commented on src/ios_gen.rs
> +            for locale in map.clone().keys() {
Я пытался разобраться с этим borrow, но никак, кроме такой реализации, не вышло)

Даже за доку по расту к этому моменту таки засел

2023-11-17 13:55 UTC, Nazeebo commented on src/ios_gen.rs
> +impl Hash for Line {
Это намеренно, мне нужно, чтобы у Line == и hash == hash были одинаковыми, потому что такого требует Set
А так как я в этих делах сравниваю именно включение/невключение ключей, то работает как надо. Каждый язык изолирован от другого, а ключи уникальны

2023-11-17 22:04 UTC, TrueWarg requested changes

2023-11-17 22:04 UTC, TrueWarg commented on src/ios_gen.rs
> +            for locale in map.clone().keys() {
Тут логично, что просит склонировать, потому что отдавая в какой-то код мутабельную ссылку, не получишь ганатний, что там будет не только модификация, но у даление ентри, ну то есть классика в некоторых языках: итерируешь по элементам списка, который сам же и меняшь в коде :smile_cat: 

Можно поменять подход:

```
fn get_absent_translations(keys: Keys<'_, Locale, StrLines>, default_lang: &Option<String>) -> HashMap<Locale, StrLines>
// внутри просто создаешь локальную переменную 
// let mut result: HashMap<Locale, StrLines> = HashMap::new();
// Клонировать в ней ничего не нужно
```

Вместе вызова
```
    // В этом случае ты передашь итератор, правда я не уверен, не будет ли в конечтом итоге у тебя копирования все равно, если ключ реализует Clone, то может быть, но в связке с итератором хз. Как миниум не будет копии всей коллекции вместе со значениями, да и так чище как по мне, потому что out params в функциях - meh. 
    let kek = fill_absent_translations(result.keys(), default_lang);
    result.extend(kek);
```

2024-02-29 09:43 UTC, merged